2020-07-08T00:21:01.1214092+03:00  [INF] Application is shutting down... (90f52c38)
2020-07-08T01:19:28.0362543+03:00  [INF] Starting server on port 8080... (e54e9051)
2020-07-08T01:19:28.1400257+03:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2020-07-08T01:19:28.1432577+03:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-07-08T01:19:28.1453600+03:00  [INF] Hosting environment: "Development" (c3307c92)
2020-07-08T01:19:28.1468547+03:00  [INF] Content root path: "D:\Documents\GitHub\MyAccounts\MyAccountsVue" (b5d60022)
2020-07-08T01:21:30.1726546+03:00 0HM12OF87KS51:00000001 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.TimeoutException: The vue-cli server did not start listening for requests within the timeout period of 0 seconds. Check the log output for error information.
   at VueCliMiddleware.TaskTimeoutExtensions.WithTimeout[T](Task`1 task, TimeSpan timeoutDelay, String message)
   at Microsoft.AspNetCore.SpaServices.Extensions.Proxy.SpaProxy.PerformProxyRequest(HttpContext context, HttpClient httpClient, Task`1 baseUriTask, CancellationToken applicationStoppingToken, Boolean proxy404s)
   at Microsoft.AspNetCore.Builder.SpaProxyingExtensions.<>c__DisplayClass2_0.<<UseProxyToSpaDevelopmentServer>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2020-07-08T01:22:48.1875268+03:00 0HM12OF87KS52:00000001 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.TimeoutException: The vue-cli server did not start listening for requests within the timeout period of 0 seconds. Check the log output for error information.
   at VueCliMiddleware.TaskTimeoutExtensions.WithTimeout[T](Task`1 task, TimeSpan timeoutDelay, String message)
   at Microsoft.AspNetCore.SpaServices.Extensions.Proxy.SpaProxy.PerformProxyRequest(HttpContext context, HttpClient httpClient, Task`1 baseUriTask, CancellationToken applicationStoppingToken, Boolean proxy404s)
   at Microsoft.AspNetCore.Builder.SpaProxyingExtensions.<>c__DisplayClass2_0.<<UseProxyToSpaDevelopmentServer>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2020-07-08T01:24:48.3306005+03:00 0HM12OF87KS52:00000002 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.TimeoutException: The vue-cli server did not start listening for requests within the timeout period of 0 seconds. Check the log output for error information.
   at VueCliMiddleware.TaskTimeoutExtensions.WithTimeout[T](Task`1 task, TimeSpan timeoutDelay, String message)
   at Microsoft.AspNetCore.SpaServices.Extensions.Proxy.SpaProxy.PerformProxyRequest(HttpContext context, HttpClient httpClient, Task`1 baseUriTask, CancellationToken applicationStoppingToken, Boolean proxy404s)
   at Microsoft.AspNetCore.Builder.SpaProxyingExtensions.<>c__DisplayClass2_0.<<UseProxyToSpaDevelopmentServer>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2020-07-08T01:24:57.5078525+03:00 0HM12OF87KS51:00000002 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.TimeoutException: The vue-cli server did not start listening for requests within the timeout period of 0 seconds. Check the log output for error information.
   at VueCliMiddleware.TaskTimeoutExtensions.WithTimeout[T](Task`1 task, TimeSpan timeoutDelay, String message)
   at Microsoft.AspNetCore.SpaServices.Extensions.Proxy.SpaProxy.PerformProxyRequest(HttpContext context, HttpClient httpClient, Task`1 baseUriTask, CancellationToken applicationStoppingToken, Boolean proxy404s)
   at Microsoft.AspNetCore.Builder.SpaProxyingExtensions.<>c__DisplayClass2_0.<<UseProxyToSpaDevelopmentServer>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2020-07-08T01:26:48.4603646+03:00 0HM12OF87KS52:00000003 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.TimeoutException: The vue-cli server did not start listening for requests within the timeout period of 0 seconds. Check the log output for error information.
   at VueCliMiddleware.TaskTimeoutExtensions.WithTimeout[T](Task`1 task, TimeSpan timeoutDelay, String message)
   at Microsoft.AspNetCore.SpaServices.Extensions.Proxy.SpaProxy.PerformProxyRequest(HttpContext context, HttpClient httpClient, Task`1 baseUriTask, CancellationToken applicationStoppingToken, Boolean proxy404s)
   at Microsoft.AspNetCore.Builder.SpaProxyingExtensions.<>c__DisplayClass2_0.<<UseProxyToSpaDevelopmentServer>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2020-07-08T01:27:06.0613576+03:00  [INF] Starting server on port 8080... (e54e9051)
2020-07-08T01:27:06.1618065+03:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2020-07-08T01:27:06.1631563+03:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-07-08T01:27:06.1642815+03:00  [INF] Hosting environment: "Development" (c3307c92)
2020-07-08T01:27:06.1656358+03:00  [INF] Content root path: "D:\Documents\GitHub\MyAccounts\MyAccountsVue" (b5d60022)
2020-07-08T01:27:30.0488761+03:00 0HM12OJGP84VE:00000002 [WRN] Sensitive data logging is enabled. Log entries and exception messages may include sensitive application data, this mode should only be enabled during development. (2b730620)
2020-07-08T01:33:56.3695608+03:00  [INF] Starting server on port 8080... (e54e9051)
2020-07-08T01:33:56.4791932+03:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2020-07-08T01:33:56.4806010+03:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-07-08T01:33:56.4817201+03:00  [INF] Hosting environment: "Development" (c3307c92)
2020-07-08T01:33:56.4832184+03:00  [INF] Content root path: "D:\Documents\GitHub\MyAccounts\MyAccountsVue" (b5d60022)
2020-07-08T01:34:07.6408319+03:00  [INF] Application is shutting down... (90f52c38)
2020-07-08T01:34:12.3151534+03:00  [INF] Starting server on port 8080... (e54e9051)
2020-07-08T01:34:12.4130277+03:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2020-07-08T01:34:12.4143597+03:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-07-08T01:34:12.4160633+03:00  [INF] Hosting environment: "Development" (c3307c92)
2020-07-08T01:34:12.4172389+03:00  [INF] Content root path: "D:\Documents\GitHub\MyAccounts\MyAccountsVue" (b5d60022)
2020-07-08T01:34:40.0947831+03:00 0HM12ONFNN4EP:00000002 [WRN] Sensitive data logging is enabled. Log entries and exception messages may include sensitive application data, this mode should only be enabled during development. (2b730620)
2020-07-08T09:32:17.4715492+03:00  [INF] Starting server on port 8080... (e54e9051)
2020-07-08T09:32:17.7163355+03:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2020-07-08T09:32:17.7183364+03:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-07-08T09:32:17.7195311+03:00  [INF] Hosting environment: "Development" (c3307c92)
2020-07-08T09:32:17.7207698+03:00  [INF] Content root path: "D:\Documents\GitHub\MyAccounts\MyAccountsVue" (b5d60022)
2020-07-08T09:33:04.5396418+03:00 0HM1312KKCVEH:00000003 [WRN] Sensitive data logging is enabled. Log entries and exception messages may include sensitive application data, this mode should only be enabled during development. (2b730620)
2020-07-08T11:36:03.2673203+03:00 0HM1312KKCVHJ:00000006 [ERR] Exception thrown on import rates: System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
 ---> System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessAuthentication(LazyAsyncResult lazyResult, CancellationToken cancellationToken)
   at System.Net.Security.SslStream.BeginAuthenticateAsClient(SslClientAuthenticationOptions sslClientAuthenticationOptions, CancellationToken cancellationToken, AsyncCallback asyncCallback, Object asyncState)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__65_0(SslClientAuthenticationOptions arg1, CancellationToken arg2, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2](Func`5 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2](Func`5 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2](Func`5 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, Object state)
   at System.Net.Security.SslStream.AuthenticateAsClientAsync(SslClientAuthenticationOptions sslClientAuthenticationOptions, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at MyAccounts.Application.Connections.BankApiService.LoadRate(Int32 currencyId, String currencyCode, DateTime date) in D:\Documents\GitHub\MyAccounts\MyAccounts.Application\Connections\BankApiService.cs:line 24
   at MyAccounts.Application.Currencies.CurrencyAppService.ImportRatesAsync(Int32 CurrencyId, DateTime fromDate, DateTime toDate) in D:\Documents\GitHub\MyAccounts\MyAccounts.Application\Currencies\CurrencyAppService.cs:line 149
   at MyAccountsVue.Controllers.CurrenciesController.ImportRates(Int32 id, LoadRatesViewModel model) in D:\Documents\GitHub\MyAccounts\MyAccountsVue\Controllers\CurrenciesController.cs:line 158 (4326b3e3)
2020-07-08T11:37:12.3620479+03:00 0HM1312KKCVHJ:00000008 [ERR] Exception thrown on import rates: Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at MyAccounts.Application.Connections.BankApiService.LoadRate(Int32 currencyId, String currencyCode, DateTime date) in D:\Documents\GitHub\MyAccounts\MyAccounts.Application\Connections\BankApiService.cs:line 26
   at MyAccounts.Application.Currencies.CurrencyAppService.ImportRatesAsync(Int32 CurrencyId, DateTime fromDate, DateTime toDate) in D:\Documents\GitHub\MyAccounts\MyAccounts.Application\Currencies\CurrencyAppService.cs:line 149
   at MyAccountsVue.Controllers.CurrenciesController.ImportRates(Int32 id, LoadRatesViewModel model) in D:\Documents\GitHub\MyAccounts\MyAccountsVue\Controllers\CurrenciesController.cs:line 158 (ae23092e)
2020-07-08T11:51:25.8621401+03:00  [INF] Starting server on port 8080... (e54e9051)
2020-07-08T11:51:25.9696015+03:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2020-07-08T11:51:25.9711985+03:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-07-08T11:51:25.9724830+03:00  [INF] Hosting environment: "Development" (c3307c92)
2020-07-08T11:51:25.9736128+03:00  [INF] Content root path: "D:\Documents\GitHub\MyAccounts\MyAccountsVue" (b5d60022)
2020-07-08T11:52:11.1018203+03:00 0HM133GCJI928:00000002 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.Net.Http.HttpRequestException: Failed to proxy the request to http://localhost:8080/js/app.js, because the request to the proxy target failed. Check that the proxy target server is running and accepting requests to http://localhost:8080/.

The underlying exception message was 'No connection could be made because the target machine actively refused it.'.Check the InnerException for more details.
 ---> System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it.
 ---> System.Net.Sockets.SocketException (10061): No connection could be made because the target machine actively refused it.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.AspNetCore.SpaServices.Extensions.Proxy.SpaProxy.PerformProxyRequest(HttpContext context, HttpClient httpClient, Task`1 baseUriTask, CancellationToken applicationStoppingToken, Boolean proxy404s)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.SpaServices.Extensions.Proxy.SpaProxy.PerformProxyRequest(HttpContext context, HttpClient httpClient, Task`1 baseUriTask, CancellationToken applicationStoppingToken, Boolean proxy404s)
   at Microsoft.AspNetCore.Builder.SpaProxyingExtensions.<>c__DisplayClass2_0.<<UseProxyToSpaDevelopmentServer>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2020-07-08T11:52:11.1349930+03:00 0HM133GCJI929:00000003 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.Net.Http.HttpRequestException: Failed to proxy the request to http://localhost:8080/js/4.js, because the request to the proxy target failed. Check that the proxy target server is running and accepting requests to http://localhost:8080/.

The underlying exception message was 'No connection could be made because the target machine actively refused it.'.Check the InnerException for more details.
 ---> System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it.
 ---> System.Net.Sockets.SocketException (10061): No connection could be made because the target machine actively refused it.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.AspNetCore.SpaServices.Extensions.Proxy.SpaProxy.PerformProxyRequest(HttpContext context, HttpClient httpClient, Task`1 baseUriTask, CancellationToken applicationStoppingToken, Boolean proxy404s)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.SpaServices.Extensions.Proxy.SpaProxy.PerformProxyRequest(HttpContext context, HttpClient httpClient, Task`1 baseUriTask, CancellationToken applicationStoppingToken, Boolean proxy404s)
   at Microsoft.AspNetCore.Builder.SpaProxyingExtensions.<>c__DisplayClass2_0.<<UseProxyToSpaDevelopmentServer>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2020-07-08T11:52:11.1399468+03:00 0HM133GCJI92B:00000001 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.Net.Http.HttpRequestException: Failed to proxy the request to http://localhost:8080/js/2.js, because the request to the proxy target failed. Check that the proxy target server is running and accepting requests to http://localhost:8080/.

The underlying exception message was 'No connection could be made because the target machine actively refused it.'.Check the InnerException for more details.
 ---> System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it.
 ---> System.Net.Sockets.SocketException (10061): No connection could be made because the target machine actively refused it.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.AspNetCore.SpaServices.Extensions.Proxy.SpaProxy.PerformProxyRequest(HttpContext context, HttpClient httpClient, Task`1 baseUriTask, CancellationToken applicationStoppingToken, Boolean proxy404s)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.SpaServices.Extensions.Proxy.SpaProxy.PerformProxyRequest(HttpContext context, HttpClient httpClient, Task`1 baseUriTask, CancellationToken applicationStoppingToken, Boolean proxy404s)
   at Microsoft.AspNetCore.Builder.SpaProxyingExtensions.<>c__DisplayClass2_0.<<UseProxyToSpaDevelopmentServer>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2020-07-08T11:53:32.1895061+03:00  [INF] Starting server on port 8080... (e54e9051)
2020-07-08T11:53:32.3436313+03:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2020-07-08T11:53:32.3452640+03:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-07-08T11:53:32.3464565+03:00  [INF] Hosting environment: "Development" (c3307c92)
2020-07-08T11:53:32.3475998+03:00  [INF] Content root path: "D:\Documents\GitHub\MyAccounts\MyAccountsVue" (b5d60022)
2020-07-08T11:53:54.4817033+03:00 0HM133HI9LH6F:00000002 [WRN] Sensitive data logging is enabled. Log entries and exception messages may include sensitive application data, this mode should only be enabled during development. (2b730620)
